# KallistiOS ##version##
#
# utils/naominetboot/Makefile
# Copyright (C) 2020 Lawrence Sebald
#

all: naominetboot

naominetboot: naominetboot.c
	$(CC) -o naominetboot naominetboot.c

distclean:
	-rm -f naominetboot
