var searchData=
[
  ['c11_0',['C11',['../group__threading__c11.html',1,'']]],
  ['cables_1',['Cables',['../group__video__cables.html',1,'']]],
  ['cache_2',['Cache',['../group__system__cache.html',1,'']]],
  ['cacheability_20settings_3',['Cacheability Settings',['../group__mmu__cache__values.html',1,'']]],
  ['calls_4',['System Calls',['../group__system__calls.html',1,'']]],
  ['camera_5',['Camera',['../group__peripherals__camera.html',1,'']]],
  ['capabilities_6',['Capabilities',['../group__controller__caps.html',1,'Capabilities'],['../group__controller__query__caps.html',1,'Querying Capabilities']]],
  ['capability_20groups_7',['Capability Groups',['../group__controller__caps__groups.html',1,'']]],
  ['capacity_8',['Memory Capacity',['../group__hw__memsizes.html',1,'']]],
  ['card_9',['SD Card',['../group__vfs__sd.html',1,'']]],
  ['card_20function_10',['Memory Card Function',['../group__maple__memcard.html',1,'']]],
  ['cdda_20read_20modes_11',['CDDA Read Modes',['../group__cdda__read__modes.html',1,'']]],
  ['channel_20commands_12',['Channel Commands',['../group__audio__aica__ch__cmd.html',1,'']]],
  ['channel_20start_20values_13',['Channel Start Values',['../group__audio__aica__ch__start.html',1,'']]],
  ['channel_20update_20values_14',['Channel Update Values',['../group__audio__aica__ch__update.html',1,'']]],
  ['channels_15',['Channels',['../group__tmus.html',1,'']]],
  ['character_20drawing_16',['Character Drawing',['../group__bfont__char.html',1,'']]],
  ['checks_17',['Checks',['../group__version__comptime__check.html',1,'Checks'],['../group__version__runtime__check.html',1,'Checks']]],
  ['clamp_20mode_18',['U/V Clamp Mode',['../group__pvr__uv__clamp.html',1,'']]],
  ['clamping_20toggle_19',['Clamping Toggle',['../group__pvr__colclamp__switch.html',1,'']]],
  ['clock_20',['Real-Time Clock',['../group__rtc.html',1,'']]],
  ['clock_20function_21',['Clock Function',['../group__maple__clock.html',1,'']]],
  ['codes_22',['Codes',['../group__networking__icmpv6__unreachable.html',1,'Destination Unreachable Codes'],['../group__asic__events.html',1,'Event Codes'],['../group__maple__functions.html',1,'Function Codes'],['../group__networking__icmpv6__param__problem.html',1,'Parameter Problem Codes'],['../group__hw__regions.html',1,'Region Codes'],['../group__cd__cmd__codes.html',1,'Syscall Command Codes'],['../group__networking__icmpv6__time__exceeded.html',1,'Time Exceeded Codes']]],
  ['color_23',['Color',['../group__pvr__ctx__color.html',1,'']]],
  ['command_20bits_24',['Command Bits',['../group__bba__cbits.html',1,'']]],
  ['command_20codes_25',['Syscall Command Codes',['../group__cd__cmd__codes.html',1,'']]],
  ['command_20responses_26',['Command Responses',['../group__cd__cmd__response.html',1,'']]],
  ['command_20status_20responses_27',['Command Status Responses',['../group__cd__cmd__status.html',1,'']]],
  ['command_20values_28',['TA Command Values',['../group__pvr__commands.html',1,'']]],
  ['commands_29',['Commands',['../group__audio__aica__ch__cmd.html',1,'Channel Commands'],['../group__audio__aica__cmd.html',1,'Commands']]],
  ['commands_20and_20responses_30',['Commands and Responses',['../group__maple__cmds.html',1,'']]],
  ['compatibility_20defines_31',['Language Compatibility Defines',['../group__system__compat.html',1,'']]],
  ['compilation_32',['Compilation',['../group__pvr__primitives__compilation.html',1,'']]],
  ['compile_20time_33',['Compile-Time',['../group__version__comptime.html',1,'']]],
  ['config_20fields_34',['ISP Config Fields',['../group__fr__fields.html',1,'']]],
  ['config_20flags_35',['ISP Config Flags',['../group__fr__flags.html',1,'']]],
  ['config_20register_201_20rt_5fconfig1_20bits_36',['RTL8139C Config Register 1 (RT_CONFIG1) Bits',['../group__bba__config1bits.html',1,'']]],
  ['config_20register_204_20rt_5fconfig4_20bits_37',['RTL8139C Config Register 4 (RT_CONFIG4) Bits',['../group__bba__config4bits.html',1,'']]],
  ['config_20register_205_20rt_5fconfig5_20bits_38',['RTL8139C Config Register 5 (RT_CONFIG5) Bits',['../group__bba__config5bits.html',1,'']]],
  ['config_20register_20rt_5frxconfig_20bits_39',['RTL8139C RX Config Register (RT_RXCONFIG) bits',['../group__bba__configrx.html',1,'']]],
  ['configuration_40',['Configuration',['../group__netcfg.html',1,'']]],
  ['configuration_20flags_41',['Configuration Flags',['../group__ppp__flags.html',1,'']]],
  ['connection_20methods_42',['Connection Methods',['../group__fr__method.html',1,'']]],
  ['console_20types_43',['Console Types',['../group__hw__consoles.html',1,'']]],
  ['constants_44',['Addresses and Constants',['../group__pvr__addresses.html',1,'']]],
  ['constants_20and_20masks_45',['Constants and Masks',['../group__pvr__bitmasks.html',1,'']]],
  ['context_46',['Context',['../group__irq__context.html',1,'']]],
  ['contexts_47',['Contexts',['../group__pvr__ctx.html',1,'']]],
  ['control_20bits_48',['MII Control Bits',['../group__bba__miicb.html',1,'']]],
  ['control_20flow_49',['Control Flow',['../group__irq__ctrl.html',1,'']]],
  ['control_20registers_50',['Control Registers',['../group__sh4__cr__regs.html',1,'']]],
  ['controller_51',['Controller',['../group__controller.html',1,'Controller'],['../group__ubc.html',1,'User Break Controller']]],
  ['controller_20api_52',['DMA Controller API',['../group__dmac.html',1,'']]],
  ['counters_53',['Performance Counters',['../group__perf__counters.html',1,'']]],
  ['crc_54',['CRC',['../group__networking__crc.html',1,'']]],
  ['current_55',['Current',['../group__version__comptime__current.html',1,'Current'],['../group__version__runtime__current.html',1,'Current']]]
];
