var searchData=
[
  ['p4_20memory_20region_0',['P4 memory region',['../group__p4mem.html',1,'']]],
  ['pack_1',['Rumble Pack',['../group__peripherals__rumble.html',1,'']]],
  ['package_2',['Header Package',['../group__vmu__package.html',1,'']]],
  ['page_20size_20settings_3',['Page size settings',['../group__mmu__page__size.html',1,'']]],
  ['palettes_4',['Palettes',['../group__pvr__pal__mgmt.html',1,'']]],
  ['parameter_20problem_20codes_5',['Parameter Problem Codes',['../group__networking__icmpv6__param__problem.html',1,'']]],
  ['part_6',['Read Sector Part',['../group__cd__read__sector__part.html',1,'']]],
  ['partitions_7',['Partitions',['../group__fr__parts.html',1,'']]],
  ['paths_8',['Exit Paths',['../group__arch__retpaths.html',1,'']]],
  ['pc_9',['PC',['../group__vfs__dcload.html',1,'']]],
  ['performance_20counters_10',['Performance Counters',['../group__perf__counters.html',1,'']]],
  ['performance_20monitor_11',['Performance monitor',['../group__perf__monitor.html',1,'']]],
  ['peripherals_12',['Peripherals',['../group__peripherals.html',1,'']]],
  ['phases_13',['Automaton Phases',['../group__ppp__phases.html',1,'']]],
  ['pixel_20modes_14',['Pixel Modes',['../group__video__modes__pixel.html',1,'']]],
  ['poll_20function_15',['Events for the poll() function',['../group__poll__events.html',1,'']]],
  ['polling_16',['Polling',['../group__threading__polling.html',1,'Polling'],['../group__kbd__polling.html',1,'State Polling']]],
  ['polygon_20lists_17',['Polygon Lists',['../group__pvr__lists.html',1,'Polygon Lists'],['../group__pvr__list__mgmt.html',1,'Polygon Lists']]],
  ['port_18',['External Port',['../group__asic__events__ext.html',1,'']]],
  ['posix_19',['POSIX',['../group__vfs__posix.html',1,'POSIX'],['../group__system__posix.html',1,'POSIX'],['../group__threading__posix.html',1,'POSIX']]],
  ['powervr_20',['PowerVR',['../group__asic__events__pvr.html',1,'']]],
  ['powervr_20api_21',['PowerVR API',['../group__pvr.html',1,'']]],
  ['ppp_22',['PPP',['../group__networking__ppp.html',1,'']]],
  ['primary_20timer_23',['Primary Timer',['../group__tmu__primary.html',1,'']]],
  ['primitive_20bin_20sizes_24',['Primitive Bin Sizes',['../group__pvr__binsizes.html',1,'']]],
  ['primitives_25',['Primitives',['../group__pvr__primitives.html',1,'']]],
  ['problem_20codes_26',['Parameter Problem Codes',['../group__networking__icmpv6__param__problem.html',1,'']]],
  ['profiling_27',['Profiling',['../group__pvr__stats.html',1,'']]],
  ['protection_28',['G1 ATA protection',['../group__g1ata__protect.html',1,'']]],
  ['protection_20settings_29',['Protection Settings',['../group__mmu__prot__values.html',1,'']]],
  ['protocol_20values_30',['Protocol Values',['../group__modem__protocols.html',1,'']]],
  ['pty_31',['PTY',['../group__vfs__pty.html',1,'']]]
];
