var searchData=
[
  ['sample_20types_0',['Sample Types',['../group__audio__aica__samples.html',1,'']]],
  ['sampling_20modes_1',['Sampling Modes',['../group__pvr__filter__modes.html',1,'']]],
  ['scene_20submission_2',['Scene Submission',['../group__pvr__scene__mgmt.html',1,'']]],
  ['scif_3',['SCIF',['../group__system__scif.html',1,'']]],
  ['sd_20card_4',['SD Card',['../group__vfs__sd.html',1,'']]],
  ['section_20header_20flags_5',['Section Header Flags',['../group__elf__hdrflags.html',1,'']]],
  ['section_20header_20types_6',['Section Header Types',['../group__elf__sections.html',1,'']]],
  ['section_20indices_7',['Special Section Indices',['../group__elf__specsec.html',1,'']]],
  ['sector_20mode_8',['Read Sector Mode',['../group__cd__read__sector__mode.html',1,'']]],
  ['sector_20part_9',['Read Sector Part',['../group__cd__read__sector__part.html',1,'']]],
  ['settings_10',['Settings',['../group__mmu__cache__values.html',1,'Cacheability Settings'],['../group__fr__langs.html',1,'Language Settings'],['../group__mmu__prot__values.html',1,'Protection Settings'],['../group__fr__region.html',1,'Region Settings'],['../group__vmu__settings.html',1,'Settings']]],
  ['settings_11',['Page size settings',['../group__mmu__page__size.html',1,'']]],
  ['shading_20modes_12',['Shading Modes',['../group__pvr__shading__types.html',1,'']]],
  ['size_20settings_13',['Page size settings',['../group__mmu__page__size.html',1,'']]],
  ['sizes_14',['Sizes',['../group__bfont__byte__size.html',1,'Byte Sizes'],['../group__pvr__binsizes.html',1,'Primitive Bin Sizes']]],
  ['sleeping_15',['Sleeping',['../group__tmu__sleep.html',1,'']]],
  ['sockets_16',['Sockets',['../group__vfs__sockets.html',1,'Sockets'],['../group__networking__sockets.html',1,'Sockets']]],
  ['sound_20effects_17',['Sound Effects',['../group__audio__sfx.html',1,'']]],
  ['sources_18',['Sources',['../group__netcfg__srcs.html',1,'']]],
  ['space_19',['Address Space',['../group__memory.html',1,'']]],
  ['special_20section_20indices_20',['Special Section Indices',['../group__elf__specsec.html',1,'']]],
  ['specific_20flags_21',['Dreamcast-Specific Flags',['../group__kos__init__flags__dc.html',1,'']]],
  ['speed_20values_22',['Speed Values',['../group__modem__speeds.html',1,'']]],
  ['stack_20traces_23',['Stack Traces',['../group__debugging__stacktrace.html',1,'']]],
  ['start_20values_24',['Start Values',['../group__audio__aica__ch__start.html',1,'Channel Start Values'],['../group__pvr__go.html',1,'Init/Start Values']]],
  ['state_25',['State',['../group__pvr__global.html',1,'Global State'],['../group__irq__state.html',1,'State']]],
  ['states_26',['States',['../group__maple__frame__states.html',1,'Frame States'],['../group__key__states.html',1,'Key States']]],
  ['status_27',['Subcode Audio Status',['../group__cd__subcode__audio.html',1,'']]],
  ['status_20bits_28',['Status Bits',['../group__bba__ibits.html',1,'Interrupt Status Bits'],['../group__bba__miisb.html',1,'MII Status Bits'],['../group__bba__rbits.html',1,'Receive Status Bits'],['../group__bba__tbits.html',1,'RTL8139C Transmit Status Bits']]],
  ['status_20responses_29',['Command Status Responses',['../group__cd__cmd__status.html',1,'']]],
  ['status_20values_30',['Status Values',['../group__cd__status__values.html',1,'']]],
  ['statuses_31',['ATA Statuses',['../group__cd__cmd__ata__status.html',1,'']]],
  ['store_20queues_32',['Store Queues',['../group__store__queues.html',1,'']]],
  ['streaming_33',['Streaming',['../group__audio__streaming.html',1,'']]],
  ['stride_20management_34',['Texture Stride Management',['../group__pvr__txr__stride.html',1,'']]],
  ['string_20drawing_35',['String Drawing',['../group__bfont__string.html',1,'']]],
  ['structure_36',['Structure',['../group__bfont__indicies.html',1,'']]],
  ['subcode_20audio_20status_37',['Subcode Audio Status',['../group__cd__subcode__audio.html',1,'']]],
  ['subcode_20type_38',['Read Subcode Type',['../group__cd__read__subcode__type.html',1,'']]],
  ['submission_39',['Scene Submission',['../group__pvr__scene__mgmt.html',1,'']]],
  ['symbol_20binding_20types_40',['Symbol Binding Types',['../group__elf__binding.html',1,'']]],
  ['symbol_20types_41',['Symbol Types',['../group__elf__symtype.html',1,'']]],
  ['syscall_20command_20codes_42',['Syscall Command Codes',['../group__cd__cmd__codes.html',1,'']]],
  ['system_43',['System',['../group__system.html',1,'']]],
  ['system_20calls_44',['System Calls',['../group__system__calls.html',1,'']]]
];
